### ISSUE TITLE
Watcher not working on Windows

### ISSUE THREAD

**Issue by dmarcos** [supermedium/aframe-watcher#2]
After following the instructions with the `index.html` below in local directory (added id's to the entities as described in Readme): 
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hello, WebVR! • A-Frame</title>
    <meta name="description" content="Hello, WebVR! • A-Frame">
    <script src="https://aframe.io/releases/0.9.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene background="color: #ECECEC">
      <a-box id="box" position="-1 0.5 -3" rotation="0 45 0" color="#4CC3D9" shadow></a-box>
      <a-sphere id="sphere" position="0 1.25 -5" radius="1.25" color="#EF2D5E" shadow></a-sphere>
      <a-cylinder id="cylinder" position="1 0.75 -3" radius="0.5" height="1.5" color="#FFC65D" shadow></a-cylinder>
      <a-plane id="plane" position="0 0 -4" rotation="-90 0 0" width="4" height="4" color="#7BC8A4" shadow></a-plane>
    </a-scene>
  </body>
</html> 
```

After running the watcher I can modify / save changes. The inspector prompts to confirm changes as described in README but nothing happens. `index.html` is not modified and there are no errors in console. I noticed that I cannot kill the `aframe-watcher` with `Ctrl+C` after confirming changes but I can continue make / confirming changes from inspector at no effect.

**Comment by ngokevin** [comment]
Doesn't work on primitives right now, but I have a patch locally that makes it support it.

**Comment by ngokevin** [comment]
https://github.com/supermedium/aframe-watcher/commit/49a0553bd2ab1d5236b0affab8f4d4804e204d55
